name: Documentation

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: update Typescript
        run: npm update -g typescript

      - name: build documentation
        run: |
          npm install -D
          npm run build --if-present
          npx typedoc --out docs src
          cp -r examples dist ressources docs/
          touch docs/.nojekyll
        env:
          CI: true

      - name: deploy documentation
        uses: JamesIves/github-pages-deploy-action@releases/v3
        if: github.ref == 'refs/heads/master'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: docs
